# -*- coding: utf-8 -*-
"""entropy_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEDEUJSAE_bIM5cFicntzFgH7n2FuR5S
"""

# =============================================================================
# CÁLCULO DE SAMPLE ENTROPY (SampEn)
# =============================================================================

sampen_results = []

print("=" * 65)
print("  CÁLCULO DE SAMPLE ENTROPY")
print(f"  Parámetros: m={SAMPEN_M}, r={SAMPEN_R}·std(señal)")
print("=" * 65)

for group_name in GROUPS:
    if group_name not in ecg_data:
        continue
    print(f"\n📊 {group_name}:")

    for filename, signal in ecg_data[group_name].items():
        try:
            r_value = SAMPEN_R * np.std(signal)

            # SampEn con EntropyHub
            # Retorna: (SampEn_array, A, B)
            result = EH.SampEn(signal, m=SAMPEN_M, r=r_value)
            sampen_vals = result[0]  # Array de SampEn para m=0,1,...,M
            sampen_m = sampen_vals[-1]  # Valor para m=SAMPEN_M

            # También con señal normalizada (z-score)
            sig_norm = (signal - np.mean(signal)) / np.std(signal)
            result_norm = EH.SampEn(sig_norm, m=SAMPEN_M, r=SAMPEN_R)
            sampen_norm = result_norm[0][-1]

            sampen_results.append({
                'Grupo': group_name,
                'Archivo': filename.replace('.txt',''),
                'N_latidos': len(signal),
                'Std_señal': np.std(signal),
                'r_absoluto': r_value,
                'SampEn': sampen_m,
                'SampEn_norm': sampen_norm
            })

            print(f"   ✅ {filename}: SampEn={sampen_m:.6f} | SampEn_norm={sampen_norm:.6f}")

        except Exception as e:
            print(f"   ❌ {filename}: {e}")
            sampen_results.append({
                'Grupo': group_name,
                'Archivo': filename.replace('.txt',''),
                'N_latidos': len(signal),
                'Std_señal': np.std(signal),
                'r_absoluto': SAMPEN_R * np.std(signal),
                'SampEn': np.nan,
                'SampEn_norm': np.nan
            })

df_sampen = pd.DataFrame(sampen_results)

print("\n📋 RESULTADOS SAMPLE ENTROPY:")
display(df_sampen)

df_sampen.to_csv(os.path.join(RESULTS_PATH, 'tablas', 'sample_entropy.csv'), index=False)
print("✅ Tabla guardada: sample_entropy.csv")



# =============================================================================
# CÁLCULO DE PERMUTATION ENTROPY (PermEn) - CORREGIDA
# =============================================================================
import math  # <-- Importar math de Python estándar

permen_results = []

print("=" * 65)
print("  CÁLCULO DE PERMUTATION ENTROPY")
print(f"  Parámetros: m={PERMEN_M}, τ={PERMEN_TAU}")
print(f"  Máximo teórico: ln({PERMEN_M}!) = {np.log2(math.factorial(PERMEN_M)):.4f} bits")
print("=" * 65)

for group_name in GROUPS:
    if group_name not in ecg_data:
        continue
    print(f"\n📊 {group_name}:")

    for filename, signal in ecg_data[group_name].items():
        try:
            # PermEn con EntropyHub
            # Retorna: (PermEn_array, Pnorm_array, cPE)
            result = EH.PermEn(signal, m=PERMEN_M, tau=PERMEN_TAU)
            permen_vals = result[0]
            permen_norm_vals = result[1]

            permen_m = permen_vals[-1]
            permen_norm_m = permen_norm_vals[-1]

            permen_results.append({
                'Grupo': group_name,
                'Archivo': filename.replace('.txt',''),
                'N_latidos': len(signal),
                'PermEn': permen_m,
                'PermEn_norm': permen_norm_m
            })

            print(f"   ✅ {filename}: PermEn={permen_m:.6f} | PermEn_norm={permen_norm_m:.6f}")

        except Exception as e:
            print(f"   ❌ {filename}: {e}")
            permen_results.append({
                'Grupo': group_name,
                'Archivo': filename.replace('.txt',''),
                'N_latidos': len(signal),
                'PermEn': np.nan,
                'PermEn_norm': np.nan
            })

df_permen = pd.DataFrame(permen_results)

print("\n📋 RESULTADOS PERMUTATION ENTROPY:")
display(df_permen)

df_permen.to_csv(os.path.join(RESULTS_PATH, 'tablas', 'permutation_entropy.csv'), index=False)
print("✅ Tabla guardada: permutation_entropy.csv")