# -*- coding: utf-8 -*-
"""visibility_graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdfmRYzD2f6hlbZjLyHnIf6h5fvBXdPZ
"""

"""
=============================================================================
CONSTRUCCIÓN DE GRAFOS DE VISIBILIDAD
=============================================================================
"""

def visibility_graph(series: np.ndarray) -> nx.Graph:
    """
    Construye un grafo de visibilidad natural (NVG).

    Dos nodos i y j están conectados si todos los puntos intermedios k cumplen:
    y_k < y_i + (y_j - y_i) * (k - i) / (j - i)
    """
    n = len(series)
    G = nx.DiGraph()
    G.add_nodes_from(range(n))

    # Añadir atributos de nodo
    for i in range(n):
        G.nodes[i]['value'] = series[i]
        G.nodes[i]['time'] = i

    # Construir aristas basadas en visibilidad
    for i in range(n - 1):
        for j in range(i + 1, n):
            visible = True
            for k in range(i + 1, j):
                y_line = series[i] + (series[j] - series[i]) * (k - i) / (j - i)
                if series[k] >= y_line:
                    visible = False
                    break
            if visible:
                G.add_edge(i, j)

    return G


def horizontal_visibility_graph(series: np.ndarray) -> nx.Graph:
    """
    Construye un grafo de visibilidad horizontal (HVG).

    Dos nodos i y j están conectados si todos los puntos intermedios k cumplen:
    y_k < min(y_i, y_j)
    """
    n = len(series)
    G = nx.DiGraph()
    G.add_nodes_from(range(n))

    for i in range(n):
        G.nodes[i]['value'] = series[i]
        G.nodes[i]['time'] = i

    for i in range(n - 1):
        for j in range(i + 1, n):
            min_val = min(series[i], series[j])
            visible = True
            for k in range(i + 1, j):
                if series[k] >= min_val:
                    visible = False
                    break
            if visible:
                G.add_edge(i, j)

    return G


def construir_grafo(series: np.ndarray, graph_type: str = 'visibility') -> nx.Graph:
    """Wrapper para construir el grafo según el tipo especificado."""
    if graph_type == 'horizontal':
        return horizontal_visibility_graph(series)
    return visibility_graph(series)


print("✅ Funciones de construcción de grafos definidas")



import numpy as np
import networkx as nx
from typing import Dict

@dataclass
class NetworkMetrics:
    """Contenedor para métricas de red."""
    num_nodes: int
    num_edges: int
    density: float
    avg_degree: float
    avg_clustering: float
    avg_path_length: float
    diameter: int
    assortativity: float
    transitivity: float
    avg_betweenness: float
    avg_closeness: float

    def to_dict(self) -> dict:
        return {
            'Nodos': self.num_nodes,
            'Aristas': self.num_edges,
            'Densidad': self.density,
            'Grado_Promedio': self.avg_degree,
            'Clustering_Promedio': self.avg_clustering,
            'Longitud_Camino_Promedio': self.avg_path_length,
            'Diametro': self.diameter,
            'Asortatividad': self.assortativity,
            'Transitividad': self.transitivity,
            'Betweenness_Promedio': self.avg_betweenness,
            'Closeness_Promedio': self.avg_closeness
        }

def calcular_metricas(G: nx.Graph) -> NetworkMetrics:
    """Calcula métricas comprehensivas de una red."""

    # Métricas básicas
    num_nodes = G.number_of_nodes()
    num_edges = G.number_of_edges()
    density = nx.density(G)

    # Grado
    degrees = [d for n, d in G.degree()]
    avg_degree = np.mean(degrees) if degrees else 0

    # Clustering
    avg_clustering = nx.average_clustering(G)
    transitivity = nx.transitivity(G)

    # Caminos (componente conectado más grande)
    # For directed graphs, use is_weakly_connected and weakly_connected_components
    if nx.is_weakly_connected(G):
        largest_cc = G
    else:
        largest_cc = G.subgraph(max(nx.weakly_connected_components(G), key=len)).copy()

    if largest_cc.number_of_nodes() > 1:
        try:
            avg_path_length = nx.average_shortest_path_length(largest_cc)
            diameter = nx.diameter(largest_cc)
        except nx.NetworkXNoPath: # Specific error for no path if no path exists
            avg_path_length = 0
            diameter = 0
        except Exception: # Catch other potential errors
            avg_path_length = 0
            diameter = 0
    else:
        avg_path_length = 0
        diameter = 0

    # Asortatividad
    try:
        assortativity = nx.degree_assortativity_coefficient(G)
        if np.isnan(assortativity):
            assortativity = 0
    except Exception:
        assortativity = 0

    # Centralidades (con manejo de errores para redes pequeñas)
    try:
        betweenness = nx.betweenness_centrality(G)
        avg_betweenness = np.mean(list(betweenness.values()))
    except Exception:
        avg_betweenness = 0

    try:
        closeness = nx.closeness_centrality(G)
        avg_closeness = np.mean(list(closeness.values()))
    except Exception:
        avg_closeness = 0

    return NetworkMetrics(
        num_nodes=num_nodes,
        num_edges=num_edges,
        density=density,
        avg_degree=avg_degree,
        avg_clustering=avg_clustering,
        avg_path_length=avg_path_length,
        diameter=diameter,
        assortativity=assortativity,
        transitivity=transitivity,
        avg_betweenness=avg_betweenness,
        avg_closeness=avg_closeness
    )


def calcular_metricas_extendidas(G: nx.Graph) -> Dict:
    """Calcula métricas adicionales de la red."""
    degrees = [d for n, d in G.degree()]

    metricas = {
        'grado_max': max(degrees) if degrees else 0,
        'grado_min': min(degrees) if degrees else 0,
        'grado_std': np.std(degrees) if degrees else 0,
        # For directed graphs, use number_weakly_connected_components
        'num_componentes': nx.number_weakly_connected_components(G),
    }

    # Eficiencias (pueden ser costosas computacionalmente)
    try:
        metricas['eficiencia_global'] = nx.global_efficiency(G)
    except Exception:
        metricas['eficiencia_global'] = 0

    return metricas


print("✅ Funciones de métricas definidas")



"""
=============================================================================
CONSTRUCCIÓN Y VISUALIZACIÓN DE REDES - MEDITADORES
=============================================================================
"""

print("🔄 Construyendo redes de visibilidad para meditadores...")
print("   (Esto puede tomar unos minutos...)\n")

# Almacenar grafos y métricas
grafos_meditadores = {}
metricas_meditadores = {}

# Construir grafos para TaiChi
print("📍 Procesando TaiChi...")
for name, signal in data['taichi'].items():
    start_time = time.time()
    G = construir_grafo(signal, GRAPH_TYPE)
    metrics = calcular_metricas(G)
    grafos_meditadores[name] = G
    metricas_meditadores[name] = metrics
    print(f"   ✓ {name}: {G.number_of_nodes()} nodos, {G.number_of_edges()} aristas ({time.time()-start_time:.1f}s)")

# Construir grafos para Yoga
print("\n📍 Procesando Yoga...")
for name, signal in data['yoga'].items():
    start_time = time.time()
    G = construir_grafo(signal, GRAPH_TYPE)
    metrics = calcular_metricas(G)
    grafos_meditadores[name] = G
    metricas_meditadores[name] = metrics
    print(f"   ✓ {name}: {G.number_of_nodes()} nodos, {G.number_of_edges()} aristas ({time.time()-start_time:.1f}s)")

print("\n✅ Redes de meditadores construidas")



"""
=============================================================================
CONSTRUIR REDES DE VISIBILIDAD - SLEEP (CONTROL)
=============================================================================
"""

print("🔄 Construyendo redes de visibilidad para grupo Sleep...")
print("   (Esto tomará varios minutos debido a la cantidad de ventanas...)\n")

# Almacenar grafos y métricas
grafos_sleep = {}
metricas_sleep = {}

total_ventanas = sum(len(info['segments']) for info in data['sleep'].values())
print(f"   Total de ventanas a procesar: {total_ventanas}")
print("-"*60)

for name, info in data['sleep'].items():
    grafos_sleep[name] = []
    metricas_sleep[name] = []

    print(f"\n🔵 Procesando {name} ({len(info['segments'])} ventanas)...")

    for j, segment in enumerate(info['segments']):
        G = construir_grafo(segment, GRAPH_TYPE)
        metrics = calcular_metricas(G)
        grafos_sleep[name].append(G)
        metricas_sleep[name].append(metrics)

        # Mostrar progreso cada 5 ventanas
        if (j + 1) % 5 == 0 or j == len(info['segments']) - 1:
            print(f"   [{j+1}/{len(info['segments'])}] completadas")

print("\n" + "="*60)
print("✅ Redes de Sleep (control) construidas")
print(f"   Total de grafos generados: {sum(len(v) for v in grafos_sleep.values())}")



"""
=============================================================================
CELDA 8b: FUNCIÓN PARA GENERAR REDES (CON PARÁMETRO DE COLOR)
=============================================================================
"""

def visualizar_red_completa(grafo, titulo, filename, output_dir, color_nodos):
    """Genera red y guarda como PNG."""

    os.makedirs(output_dir, exist_ok=True)

    fig, ax = plt.subplots(figsize=(12, 12))

    pos = nx.spring_layout(grafo, iterations=15, seed=42)

    nx.draw(grafo, pos, ax=ax,
            node_size=10,
            node_color=color_nodos,
            edge_color='gray',
            alpha=0.3,
            with_labels=False)

    ax.set_title(titulo, fontsize=14, fontweight='bold')

    filepath = os.path.join(output_dir, f'{filename}.png')
    plt.savefig(filepath, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    return filepath


print("✅ Función actualizada con parámetro de color")



"""
=============================================================================
CELDA 8c: GENERAR REDES - MEDITADORES
=============================================================================
"""

print("="*80)
print("GENERANDO REDES DE MEDITADORES")
print("="*80)

redes_taichi_dir = f'{RESULTS_PATH}/redes_taichi'
redes_yoga_dir = f'{RESULTS_PATH}/redes_yoga'

# TAI-CHI (NARANJA)
print("\n🟠 TAI-CHI (naranja):")
for i, name in enumerate(data['taichi'].keys(), 1):
    G = grafos_meditadores[name]
    visualizar_red_completa(G, f'{name.upper()} (Tai-Chi)', f'red_{name}', redes_taichi_dir, '#F4A59B')
    print(f"   [{i}/4] ✓ {name}")

# YOGA (VERDE)
print("\n🟢 YOGA (verde):")
for i, name in enumerate(data['yoga'].keys(), 1):
    G = grafos_meditadores[name]
    visualizar_red_completa(G, f'{name.upper()} (Yoga)', f'red_{name}', redes_yoga_dir, '#A1D99B')
    print(f"   [{i}/4] ✓ {name}")

print(f"\n📁 Tai-Chi: {redes_taichi_dir}")
print(f"📁 Yoga: {redes_yoga_dir}")
print("\n✅ Meditadores completados")



"""
=============================================================================
CELDA 8d: GENERAR REDES - SLEEP (AZUL)
=============================================================================
"""



print("="*80)
print("GENERANDO REDES - SLEEP (AZUL)")
print("="*80)
print("\n⚠️ Esto tomará varios minutos...\n")

redes_sleep_dir = f'{RESULTS_PATH}/redes_sleep'
total_redes = 0

for sleep_name in data['sleep'].keys():

    subdir = f'{redes_sleep_dir}/{sleep_name}'
    num_ventanas = len(grafos_sleep[sleep_name])

    print(f"🔵 {sleep_name.upper()} ({num_ventanas} ventanas):")

    for idx, G in enumerate(grafos_sleep[sleep_name]):

        visualizar_red_completa(G, f'{sleep_name.upper()} - Ventana {idx+1}',
                               f'red_{sleep_name}_v{idx+1:03d}', subdir, '#92C5DE')

        total_redes += 1

        if (idx + 1) % 5 == 0 or (idx + 1) == num_ventanas:
            print(f"   [{idx+1}/{num_ventanas}]")

print(f"\n📁 Guardado en: {redes_sleep_dir}")
print(f"\n✅ Total: {total_redes} redes Sleep generadas")